---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgo-additional-conf
  namespace: grafana
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: pgo-additional-conf
    creationPolicy: Owner
  data:
    - secretKey: pgo-additional-conf.conf
      remoteRef:
        key: "percona-grafana-additional-config"
    - secretKey: minio.crt
      remoteRef:
        key: "percona-additional-ca"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-grafana-credentials
  namespace: grafana
spec:
  secretStoreRefs:
    - name: bitwarden-secretsmanager
      kind: ClusterSecretStore
  updatePolicy: Replace
  selector:
    secret:
      name: grafana-credentials
  data:
    - match:
        remoteRef:
          remoteKey: percona-grafana-credentials
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-postgres-credentials
  namespace: grafana
spec:
  secretStoreRefs:
    - name: bitwarden-secretsmanager
      kind: ClusterSecretStore
  updatePolicy: Replace
  selector:
    secret:
      name: postgres-credentials
  data:
    - match:
        remoteRef:
          remoteKey: percona-grafana-postgres
