apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: grafana
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: grafana-secret
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: '{{ index . "host" }}'
        POSTGRES_PORT: '{{ index . "port" }}'
        POSTGRES_USER: '{{ index . "user" }}'
        POSTGRES_PASSWORD: '{{ index . "password" }}'
        GF_SECURITY_ADMIN_PASSWORD: '{{ index . "grafana_password" }}'
  dataFrom:
    - extract:
        key: percona-grafana-credentials
    - extract:
        key: grafana-password
