global:
  storageClass: "vsphere-csi"

auth:
  enablePostgresUser: true
  existingSecret: pg-secret
  username: grafana
  database: grafana
  secretKeys:
    userPasswordKey: user-password
    adminPasswordKey: postgres-password

primary:
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  podAnnotations:
    backup/retain: "true"

readReplicas:
  enabled: false

service:
  type: ClusterIP
  ports:
    postgresql: 5432

livenessProbe:
  enabled: true
readinessProbe:
  enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true

extraDeploy:
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: grafana-postgres
      namespace: grafana
    spec:
      secretStoreRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
      target:
        name: pg-secret
        creationPolicy: Owner
      data:
        - secretKey: user-password
          remoteRef:
            key: grafana-postgres-user-password
        - secretKey: postgres-password
          remoteRef:
            key: grafana-postgres-admin-password
